# Generated by Django 4.2.2 on 2023-06-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiddenLocation_Image',
            new_name='Location_Image',
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=250)),
                ('locationAddress', models.CharField(max_length=250)),
                ('hastag', models.CharField(null=True)),
                ('locationDescription', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment_location',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.locations'),
        ),
        migrations.AlterField(
            model_name='favorites_location',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.locations'),
        ),
        migrations.AlterField(
            model_name='location_image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.locations'),
        ),
        migrations.DeleteModel(
            name='HiddenLocations',
        ),
    ]
