# Generated by Django 4.2.2 on 2023-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_hiddenlocation_image_location_image_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='hastag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tagS',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Street', 'Street'), ('Nature', 'Nature'), ('Clubs&Bar', 'Clubs&Bar'), ('Mountains', 'Mountains'), ('Historical', 'Historical'), ('Others', 'Others')], default='1', max_length=20),
        ),
    ]
