# Generated by Django 4.2.2 on 2023-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_locations_hastag_blog_tags_locations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
