# Generated by Django 4.2.2 on 2023-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userdata_is_admin_alter_userdata_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
