# Generated by Django 4.2.2 on 2023-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userdata_is_admin_alter_userdata_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
