# Generated by Django 4.2.2 on 2023-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userdata_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
