# Generated by Django 4.2.2 on 2023-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userdata_is_verified_alter_userdata_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
