# Generated by Django 4.2.2 on 2023-07-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_userdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='xxx', max_length=100, unique=True),
        ),
    ]
