# Generated by Django 4.2.2 on 2023-07-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
    ]
