# Generated by Django 4.2.2 on 2023-07-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_userdata_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply_LocationComment_Blog',
            new_name='Reply_LocationComment',
        ),
    ]
