# Generated by Django 4.2.2 on 2023-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_reply_locationcomment_blog_reply_locationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='Longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
