# Generated by Django 4.2.2 on 2023-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_locations_longitude_locations_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(default=0),
        ),
    ]
