# Generated by Django 4.2.2 on 2023-07-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_locations_longitude_alter_locations_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='locationAddress',
        ),
    ]
