# Generated by Django 4.2.2 on 2023-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_replylocationcomment_delete_reply_locationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
