# Generated by Django 4.2.2 on 2023-07-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_locationliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationliked',
            name='likeCount',
        ),
    ]
